project:
  type: website
  output-dir: docs


website:
  title: "Katharine Lee"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - publications.qmd
      - cv.qmd
      - teaching.qmd
      - lab.qmd
      - posts.qmd
      


format:
  html:
    theme: pulse
    css: styles.css
    toc: true

editor: visual

