---
title: "Curriculum Vitae"
---

# Katharine MN Lee, MS, PhD
**Assistant Professor**\
Tulane University, New Orleans, LA\
Department of Anthropology\
kLee32\@tulane.edu




## Education and Training {#education .unnumbered}
2020-2022

:   **Washington University School of Medicine**. St Louis, MO\
    *Postdoctoral Research Scholar*\
    Division of Public Health Sciences\

2020

:   **University of Illinois at Urbana-Champaign (UIUC)**. Urbana, IL\
    *PhD in Biological Anthropology*\
    *Graduate Minor in Gender & Women's Studies, Graduate Certificate in Science Communication*  Dissertation title: *Estrogen, energy, and bone: a life history approach to understanding skeletal phenotypes*\
    Dissertation advisor: Kathryn Clancy

2007

:   **Texas A&M-Texarkana**. Texarkana, TX\
    *Master of Science in Business Administration*\
    Army Materiel Command Fellows Program

2006

:   **Tulane University**. New Orleans, LA\
    *Bachelor of Science in Engineering*, field of Biomedical Engineering\
    Thesis title: *3-D Image Reconstruction of Human Brain Geometry from the Visible Human Project*\
    Thesis advisors: J.K. Francis Suh, PhD, and Richard Hart, PhD

## Professional and Research Employment {#relevant-professional-and-research-experience .unnumbered}

Washington University School of Medicine

:   St. Louis, Missouri; Aug 2020 -- Present\
    Division of Public Health Sciences

    *Postdoctoral Scholar* NIH/NCI T32 postdoctoral training program in cancer prevention and control

University of Illinois Urbana-Champaign,

:   Urbana, Illinois; Aug 2013 -- Present\

    *Research Affiliate, Department of Anthropology*, Oct 2020 -- present

    *Fellow - National Science Foundation Graduate Research Fellowship Program* Jun 2014 -- May 2019\
    Studying activity patterns and estrogen effects on bone health in young women

    *Graduate Research Assistant* Jan 2017 -- May 2017, Jan 2019 -- Jul 2019\
    Appointed as Research Assistant to Dr. Kathryn Clancy for Polish luteal reproductive function project, funded by NSF 1-200250-241004-241167; Appointed as Research Assistant to Dr. Kathryn Clancy for research on Workplace Climate and Culture at a Federal Research Facility

    *Graduate Teaching Assistant* Aug 2013 -- May 2014, Aug 2016 -- Dec 2016, Aug 2018 -- Dec 2018, Aug 2019 -- current

Dog Genetics, LLC,

:   San Antonio, TX; Feb 2011 -- Oct 2013\

    *Research Coordinator* at TSA Canine Breeding & Development Center, Lackland AFB

US Army: Army Materiel Command, Natick Soldier Research, Development, & Engineering Center,

:   Natick, MA; Sep 2007 -- Jun 2010\

    *Fellow/Biomedical Engineer, Biophysics & Biomedical Modeling Division at US Army Research Institute of Environmental Medicine (USARIEM)* Mar 2009 -- Jun 2010

    *Fellow/Biomedical Engineer, Center for Military Biomechanics Research*; Sep 2007 -- Feb 2009

US Army: Army Materiel Command,

:   ALLC, Red River Army Depot, TX 2006 -- 2007\

    *Fellow*

Ochsner Clinic Foundation,

:   New Orleans, LA 2005 -- 2006\

    *Assistant Program Coordinator for Clinical Research*, Department of Endocrinology

Vanderbilt University,

:   Nashville, TN; 2003 -- 2004\
    *Summer Research Assistant/Technical Intern*, Energy Balance Laboratory

## External grants, fellowships, and honors {#grants-and-honors .unnumbered}

2017

:   **Wenner-Gren Foundation for Anthropological Research** Dissertation Fieldwork Grant \$20,000

2017

:   **American Association of Physical Anthropologists** First runner-up as Graduate Student Liaison to AAPA Executive Committee

2017

:   **National Science Foundation** Doctoral Dissertation Improvement Grant \$31,720

2015

:   **American Philosophical Society** The Lewis and Clark Fund for Exploration and Field Research \$4500

2014

:   **National Science Foundation Graduate Research Fellowship Program** (NSF GRFP)


## Teaching Experience {#teaching-experience .unnumbered}

Certified Carpentries Instructor

:   Teaching foundational programming, data science, and data managment techniques using curriculum designed for scientists and researchers


### Washington University in St. Louis
2020 Fall

:   Applied Qualitative Methods. Teaching assistant

### University of Illinois Urbana-Champaign
2019 Fall

:   ANTH 246 - Forensic Science (online). Teaching Assistant

2018 Fall

:   ANTH 246 - Forensic Science (online). Teaching Assistant

2016 Fall

:   ANTH 103 - Anthropology in a Changing World. Teaching Assistant.

2014 Spring

:   ANTH 101 - Introduction to Anthropology. Teaching Assistant.

2013 Fall

:   ANTH 143 - Biology of Human Behavior. Teaching Assistant.

## Undergraduate Projects Supervised {#undergraduate-projects-supervised .unnumbered}

2019-2020

:   H. Ban. Undergraduate Honors Thesis: "Dietary Protein Intake and Urinary C-peptide Concentration in Regularly Menstruating Rural Polish Women"

2018-2019

:   K. Allen. Undergraduate Honors Thesis: "A Comparison of Methods for Determining Time of Ovulation"

2019

:   S. Agrawal, University of Illinois Undergraduate Researchers Initiative. Researcher Initiative Symposium poster: "Correlation of Identity Scales in Polish-American Women"

:   R. Durham, University of Illinois Undergraduate Researchers Initiative. Researcher Initiative Symposium poster: "Effects of Smoking on Cortisol Levels"

2018

:   J. Kanthak, University of Illinois Undergraduate Researchers Initiative. Researcher Initiative Symposium poster: "Female Reproductive Hormonal Variation"

2017

:   O. Shukla, University of Illinois Undergraduate Researchers Initiative. Researcher Initiative Symposium poster titled: "Inflammation and Bone Modeling in Healthy Adults"

## Publications {#publications .unnumbered}

See [Publications page](https://katharinemarielee.github.io/publications.html) or [Google Scholar](https://scholar.google.com/citations?user=oome7IYAAAAJ&hl=en&oi=ao)

## Published Abstracts {#published-abstracts .unnumbered}

2020

:   **Lee, Katharine MN,** Rogers, Mary P; Galbarczyk, Andrzej; Jasienska, Grazyna; Clancy, Kathryn BH. "Household food production shows little effect on body size and composition in two samples of young adult women." Poster presentation, accepted for annual American Association of Physical Anthropologists conference. Canceled due to COVID-19. Am J Phys Anthropol. vol 171, pg 157.

2020

:   **Lee, Katharine MN,** Rogers, Mary P; Galbarczyk, Andrzej; Jasienska, Grazyna; Clancy, Kathryn BH. "Does relative body size at menarche correspond with adult body size?" Poster presentation, accepted for annual Human Biology Association conference. Canceled due to COVID-19. Abstract publication forthcoming.

2020

:   **Lee, Katharine MN,** Rogers, Mary P; Galbarczyk, Andrzej; Jasienska, Grazyna; Clancy, Kathryn BH. "Effects of Physical Activity and Sedentary Behavior on Bone Density in Healthy Adult Women." Poster presentation, accepted for American Association of Anatomists/Evolutionary Biology conference. Canceled due to COVID-19. The FASEB Journal 34(S1). [doi: fasebj.2020.34.s1.06652](https://doi.org/10.1096/fasebj.2020.34.s1.06652)

2019

:   **Lee, Katharine MN**; Rogers, , Mary; Galbarczyk, Andzrej; Jasienska, Grazyna; Polk, John; Clancy, Kathryn. "Estrogen, energy, and skeletal biology: life history approaches to understanding skeletal phenotype in living women of reproductive age." Am J Phys Anthropol. vol 168. no S68, pg 140.

2019

:   Rogers, Mary; **Lee, Katharine MN**; Galbarczyk, Andzrej; Jasienska, Grazyna; Ripan S Malhi; Clancy, Kathryn BH. "The relationship between stress, gene methylation, and reproductive function." Am J Phys Anthropol. vol 168. no S68, pg 206-207.

2018

:   **Lee, Katharine**; Rogers, Mary; Galbarczyk, Andzrej; Jasienska, Grazyna; Polk, John; Clancy, Kathryn. "Lifestyle factors influencing frame size, grip strength, and bone density in two related populations." Am J Phys Anthropol, vol 165, no S66, p 155.

2018

:   Rogers, Mary; **Lee, Katharine MN**; Galbarczyk, Andzrej; Jasienska, Grazyna; Ripan S Malhi; Clancy, Kathryn BH. "Childhood energetic and psychosocial stressors affect adult reproductive function." Am J Phys Anthropol, vol 165, no S66, p 229.

2018

:   Rodgers, Erica; Clancy, Kathryn BH; Richey, Christina; **Lee, Katharine MN** "An inclusive workplace for all scientists." AGU Fall Meeting Abstracts. [URL](http://adsabs.harvard.edu/abs/2018AGUFM.U53A..07R)

2017

:   **Lee, Katharine**; Rogers, Mary; Galbarczyk, Andzrej; Jasienska, Grazyna; Polk, John; Clancy, Kathryn. "Bone maintenance in young healthy women: Relationships between markers of bone turnover, reproductive status, and energetics." American Journal of Human Biology, 29 (2).

2017

:   Rogers, Mary; **Lee, Katharine**; Galbarczyk, Andzrej; Jasienska, Grazyna; Malhi, Ripan; Clancy, Kathryn. "Investigating combined effects of childhood environment and age at menarche on adult reproductive hormones." American Journal of Human Biology, 29 (2).

2016

:   **Lee, Katharine**; Rogers, Mary; Galbarczyk, Andzrej; Jasienska, Grazyna; Polk, John; Clancy, Kathryn. "Physical activity and anthropometry effects on bone turnover biomarkers in rural Polish women." Am J Phys Anthropol, vol 159, no. S62, p 205.

2016

:   Rogers, Mary; **Lee, Katharine**; Galbarczyk, Andzrej; Jasienska, Grazyna; Malhi, Ripan; Clancy, Kathryn. "Investigating varition in age at menarche: relationships between gene methylation and reproductive traits in rural Polish women." Am J Phys Anthropol 159, p 271.

2016

:   Clancy, Kathryn; Rogers, Mary; **Lee, Katharine**; Galbarczyk, Andzrej; Jasienska, Grazyna. "Environmental factors associated with luteal phase endometrial thickness in a sample of rural Polish women." Am J Phys Anthropol 159, p 117.

2015

:   **Lee, Katharine M**; Rogers, Mary P; Galbarczyk, Andzrej; Jasienska, Grazyna; Clancy, Kathryn B; Polk, John D. 2015. "Physical activity levels in women of reproductive age in rural Poland," Am J Phys Anthropol, vol. 156, no. S60.

2015

:   Rogers, Mary P; **Lee, Katharine M**; Galbarczyk, Andzrej; Jasienska, Grazyna; Malhi, Ripan; Clancy, Kathryn B. 2015. "CYP19A1 methylation: life history factors’ effects on the genome." Am J Phys Anthropol, vol. 156, no. S60.

## Technical Reports and White Papers {#technical-reports-and-white-papers .unnumbered}

2014

:   Sinn, David L; Fratkin, Jamie L; Bensky, Miles; McGarrity, Monica E; **Lee, Katharine M**; and Gosling, Samuel D. Tasks 1.5, 1.6, and 1.7 Combined Report -- Task analyses to define characteristics of successfully deployed detector dogs. US Department of Homeland Security, Contract HSHQDC-10-C-00085: "Improving the Effectiveness of Detector-Dog Selection and Training through Measurement of Behavior and Temperament".

2013

:   Sinn, David L; McGarrity, Monica E; **Lee, Katharine M**; DeBono, Stephen, Fratkin, Jamie L; Bensky, Miles, Banks, Sean; and Gosling, Samuel D. Task 4.6 Report -- REDCap database development and handbook. US Department of Homeland Security, Contract HSHQDC-10-C-00085: "Improving the Effectiveness of Detector-Dog Selection and Training through Measurement of Behavior and Temperament".

2012

:   Hare, Elizabeth and **Lee, Katharine**. "Genetic Linkage Analysis (Task 3) of Detector Canines in the TSA Canine Breeding and Development Center Population." Produced under DHS Contract HSHQDC-10-C-00185.

2010

:   **Lee, Katharine**. "Effects of increased helmet weight on the ground soldier." Internal white paper prepared for helmet and helmet-borne equipment development team.

## Invited Panels, Presentations, and Guest Lectures {#invited-panels .unnumbered}

2019

:   "Participating in an inclusive, productive lab." Sep 13, 2019. Panel at 21st Century Scientists Inclusive Lab Leader - Grad workshop, invited by Dr. Kathryn Clancy.

2019

:   "Menstruation, models, and metaphors". Apr 11, 2019. Guest lecture for Anth 379 *Medical Anthropology*, invited by Emma Verstraete.

2019

:   "Menstruation: evolutionary and medical perspectives." Feb 20, 2019. Guest lecture for Anth 249 *Evolution and Human Disease*, invited by Dr. Mary Rogers.

2018

:   "Hesitant Data Science Session II: Data/Programming." Sep 27, 2018, organized by Illinois Data Science Initiative at the University of Illinois at Urbana-Champaign and hosted by the National Center for Supercomputing Applications for 2nd annual Data Science Day at UIUC.

2018

:   "Life history tradeoffs affecting bone maintenance and development in premenopausal Polish and Polish-American women." May 2, 2018, Guest lecture for Anth 102 *Human Origins and Culture*, invited by Alexandra Zachwieja.

2018

:   "Life history tradeoffs affecting bone maintenance and development in premenopausal Polish and Polish-American women." Apr 26, 2018, Department of Anthropology Colloquium talk, hosted by the Department of Anthropology, University of Illinois at Urbana-Champaign.

2018

:   "Beyond #MeToo in Tech and Academic Workplaces." Apr 4, 2018, organized by Women\@NCSA and hosted by the National Center for Supercomputing Applications.

2016

:   "Gender and Health." Oct 5, 2016. Guest lecture for Anth 103 *Anthropology in a Changing World*, invited by Dr. Krystal Smalls.

## Other Posters and Presentations {#other-posters-and-presentations .unnumbered}

2019

:   Participant in Department of Gender and Women's Studies Symposium, titled "Solidarities of Difference." Sept 20, 2019.

2018

:   **Lee, Katharine MN.** "Cripping Menstruation: Reframing Menstrual Research using Critical Disability Studies and Crip Theory." 46th annual meeting of The Canadian Association for Physical Anthropology-L’Association Canadienne D’Anthropologie Physique. Oct/Nov 2018.

2018

:   **Lee, Katharine MN,** Rogers, Mary P; Galbarczyk, Andrzej; Jasienska, Grazyna; Polk, John D; Clancy, Kathryn BH. "Physical activity in women of reproductive age in a transitioning rural Polish population." Poster presented at Wisconsin Symposium on Feminist Biology. October 5, 2018.

2017

:   **Lee, Katharine MN**; Rogers, Mary P; Galbarczyk, Andrzej; Jasienska, Grazyna; Polk, John D; Clancy, Kathryn BH. "Bone maintenance as a result of reproductive and energetic status: a life history perspective." 4th Conference of the Polish Society for Human and Evolution Studies (Polskie Towarzusto Nauk o Człowieku i Ewolucji). Krakow, Poland. September 2017.

2016

:   **Lee, Katharine**; Rogers, Mary; Galbarczyk, Andzrej; Jasienska, Grazyna; Polk, John; Clancy, Kathryn."Habitual physical activity: considering health behavior from a broader perspective (poster presentation)" Annual meeting of International Society for Evolution, Medicine, and Public Health. Durham, North Carolina. June 2016.

2016

:   **Lee, Katharine MN.** "Bone health: Reproduction and physical activity." UIUC Department of Anthropology annual research symposium. March 5, 2016.

2013

:   **Lee, Katharine M**; Thomas, Scott; and Hare, Elizabeth. "Evaluation of developmental weight gain and factors in early rearing on hip health as evaluated by PennHIP". Poster presentation at the 2013 International Working Dogs Conference.

2010

:   **Lee, Katharine M**; Buller, Mark J; Tharion, William J; Pisani, Justin; Gordon, S Robert; and Beidleman, Beth A. "Utility of simple algorithms in heart rate signal quality assessments". Poster Presentation at the 2010 Annual Fall Meeting of the Biomedical Engineering Society.

2009

:   Coyne, Megan E; Hasselquist, Leif; Schiffman, Jeffrey M; Gregorczyk, Karen N; **Nobes, Katharine M**; Adams, Albert; Bensel, Carolyn K. "Oxygen consumption output increases during steady-state submaximal prolonged heavy load carriage". Medicine & Science in Sports & Exercise. Vol 42, Issue 5. P 102. May 2009. Poster presented by M. Coyne at the American College of Sports Medicine annual conference.

2007

:   Gordon, Theresa; **Nobes, Katharine**; Nauman, Eric A; and Burshell, Alan L. "Biomechanics of Scoliosis and Its Effects on Postmenopausal Women." Platform presentation, presented by T. Gordon at the 2007 Annual Fall Meeting of the Biomedical Engineering Society.

## Published Software {#published-software .unnumbered}

2018

:   **Lee, Katharine MN.** R Code in support of publication. <https://doi.org/10.5281/zenodo.1308115>

## Language Competence {#language-competence .unnumbered}

Intermediate German\
Beginning/Intermediate Polish

## Technical and Research Skills {#technical-skills .unnumbered}

Computing: R, MATLAB, LaTeX, Markdown, Git, Jekyll, Hugo\
Data planning and data management\
Anthropometry (height, weight, circumferences, body segment measures)\
ELISA hormone analysis methods\
Design, implementation, and promotion of academic and research-related organizational strategies\
Experience with clinical and university IRB processes for human subjects research\
Experience with IACUC process for canine research\

## Service {#service .unnumbered}

**Manuscript review:**

:   American Journal of Human Biology, PeerJ

**The Carpentries**

:   2019-current\
    *Certified Software & Data Carpentry Instructor,* The Carpentries teach foundational coding and data science skills to researchers worldwide.

**21st Century Scientist Working Group**

:   UIUC; 2014-current\
    *Founding Member* Group of faculty, staff, and students at the University of Illinois interested in public engagement in science and making science more inclusive.

**Graduate representative to Department of Anthropology Faculty Meetings**

:   UIUC; 2016-2018

**Association of Biological Anthropologists at UIUC**

:   UIUC; 2013-current\
    *Treasurer 2013-2016, President 2017-2018*

**Field work, Science, and Sexual Assault: Academic field site safety should not be an afterthought**

:   UIUC; Oct 30, 2014 -- *Organized panel* to discuss field site safety and university policies. Panel included Kathryn Clancy and representatives from UIUC Women's Resource Center and the UIUC Office of Diversity, Equity, and Access.

**Anthropology Undergraduate Research Capstone Conference**

:   UIUC *Invited Judge, Spring 2014*

## Community outreach talks and presentations {#outreach-talks-and-presentations .unnumbered}

**Science Café**

:   Sponsored by the UIUC Institute of Genomic Biology and Beckman Institute December 5, 2018. Title: "Peak Bone Mass: What does it mean? Why do we care?""

## Professional Society Memberships {#professional-society-memberships .unnumbered}

American Anthropological Association (2016-current)\
American Association of Physical Anthropologists (2014-current)\
American Association for Anatomy (2019-current)\
American Society for Bone and Mineral Research (2014-current)\
Human Biology Association (2014-current)\
IEEE Engineering in Medicine and Biology Society (2006-current)\
IEEE Women in Engineering (2008-current)\
Biomedical Engineering Society (2004-2010)
