---
title: "Publications"
---

2023 Lee, Katharine MN; Rushovich, Tamara; Gompers, Annika; Lockhart, Jeffrey W; Worthington Steve; Richardson, Sarah S. “A Gender Hypothesis of sex disparities in adverse drug events”. Social Science & Medicine. Vol 339. doi: 10.1016/j.socscimed.2023.116385

2023 Rushovich, Tamara; Gompers, Annika; Lockhart, Jeffrey W; Richardson, Sarah S; Worthington Steve; Omidiran, Ife; Lee, Katharine MN. “Adverse Drug Events by Sex After Adjusting for Baseline Rates of Drug Use.” JAMA Netw Open. 2023;6(8):e2329074. doi:10.1001/jamanetworkopen.2023.29074

2023 Wiedenman, Eric; Lee, Katharine MN; Hunleth, Jean. “The adult in the room: The push and pull of parental involvement in research with children.” Childhood. <https://doi.org/10.1177/09075682231176899>

2023 Lee, Katharine MN; Hunleth, Jean; Rolf, Liz; Maki, Julia; Lewis-Thames, Marquita; Oestmann, Kevin; James, Aimee. “Distance and Transportation Barriers to Colorectal Cancer Screening in a Rural Community.” Journal of Primary Care & Community Health 14 (January 2023): 215013192211471. <https://doi.org/10.1177/21501319221147126> .

2022 Danielsen, Anne Caroline; Boulicault, Marion; Gompers, Annika; Rushovich, Tamara; Lee, Katharine MN; Richardson, Sarah S. “How cumulative statistics can mislead: The temporal dynamism of sex disparities in COVID-19 mortality in New York State.” Int J Environ Res Public Health, no. 21: 14066. doi: 10.3390/ijerph192114066

2022 Eyre, Alexander W; Zapata, Isain; Hare, Elizabeth; Lee, Katharine MN; Essler, Jennifer L; Otto, Cynthia; Serpell, James A; Alvarez, Carlos E. “Genome scanning of negative selection in a canine model of complex learning.” Sci Rep 12, 14984. doi: 10.1038/s41598-022-18698-4

2022 Lee, Katharine MN; Junkins, Eleanor J; Fatima, Urooba A; Cox, Maria L; Clancy, Kathryn BH. “Investigating trends in those who experience menstrual bleeding changes after SARS-CoV-2 vaccination.” Science Advances. Vol 8(28). doi: 10.1126/sciadv.abm7201. News Coverage (partial list): New York Times, Science News, Popular Science, Marie Claire (Brazil), BBC’s “The Naked Scientists” podcast, NBC News, Today.com, Medical News Today

2022 Boulicault, Marion; Gompers, Annika; Lee, Katharine MN; Shattuck-Heidorn, Heather. “A Feminist Approach to COVID-19 Data on Sex Disparities.” IJFAB: International Journal of Feminist Approaches to Bioethics. Vol 15, no. 1. pp167-174. doi: 10.3138/ijfab-15.1.29

2022 Ban, Hayley E; Lee, Katharine MN; Rogers-LaVanne, Mary P; Zabłocka-Słowińska, Katarzyna; Galbarczyk, Andrzej; Jasienska, Grazyna; Clancy, Kathryn BH. “Dietary Protein Source Matters for Changes in Inflammation Measured by Urinary C- Reactive Protein in Rural Polish Women.” Am J Biol Anthropol. Vol 178, Issue 1. pp 182-190. doi: 10.1002/ajpa.24502

2022 Danielsen, Ann Caroline; Lee, Katharine MN; Boulicault, Marion; Rushovich, Tamara; Gompers, Annika; Tarrant, Amelia; Reiches, Meredith; Shattuck-Heidorn, Heather; Miratrix, Luke Weisman; Richardson, Sarah S. “Sex Disparities in COVID-19 Outcomes in the United States: Quantifying and Contextualizing Variation.” Social Science & Medicine. Vol. 294. doi: 10.1016/j.socscimed.2022.114716 News Coverage: New York Times

2021 Lee, Katharine MN; Rogers-LaVanne, Mary P; Galbarczyk, Andrzej; Jasienska, Grazyna; Clancy, Kathryn BH. "Bone density and frame size in adult women: effects of body size, habitual use, and life history." Am J Hum Biol. vol 33(2). doi: 10.1002/ajhb.23502 Invited Submission: Special Issue on Biocultural Approaches to the Plasticity of the Human Skeleton.

2020 Rogers, Mary P; Lee, Katharine MN; Galbarczyk, Andrzej; Klimek, Magdalena; Klein, Laura; Zabłocka-Słowińska, Katarzyna; Jasienska, Grazyna; Clancy, Kathryn. "Declining ages at menarche in an agrarian rural region of Poland." Am J Hum Biol. vol 32(3). doi:10.1002/ajhb.23362

2020 Rodrigues, Michelle A; Sanford, Summer R; Rogers, Mary P; Lee, Katharine MN; Wilson, Meredith A; Amos, Jennifer; Hunter, Carla D; Clancy, Kathryn BH. "From maternal tending to adolescent befriending: the adolescent transition of social support." Am J Primatol. doi:10.1002/ajp.23050

2019 Richey, Christina Rae; Lee, Katharine MN; Rodgers, Erica; Clancy, Kathryn BH. "Gender and sexual minorities in astronomy and planetary science face increased risks of harassment and assault." Bulletin of the AAS. doi: 10.3847/25c2cfeb.c985281e

2019 Lee, Katharine MN; Rogers, Mary P; Galbarczyk, Andrzej; Jasienska, Grazyna; Clancy, Kathryn BH. "Physical activity in women of reproductive age in a transitioning rural Polish population." Am J Hum Biol. 31(3):e23231.doi: 10.1002/ajhb.23231

2017 Clancy, Kathryn BH; Lee, Katharine MN; Rodgers, Erica; Richey, Christina Rae. "Double jeopardy in astronomy and planetary science: women of color face greater risks of gendered and racial harassment." J. Geophys. Res. Planets, 122, doi:10.1002/2017JE005256. News coverage (partial list): Physics Today, American Scientist, Eos Vox Top downloaded article 2017-2018

2009 Routh, R Hank; Lee, Katharine M; Burshell, Alan L; and Nauman, Eric A. "The effects of anti-resorptive therapies and estrogen withdrawal in adult scoliosis measured by sub-segmental vertebral BMD analysis." Bone. Vol 45, Issue 2. pp 193-199. doi: 10.1016/j.bone.2009.03.652

2020

:   **Lee, Katharine MN**; Rogers, Mary P; Galbarczyk, Andrzej; Jasienska, Grazyna; Clancy, Kathryn BH. "Bone density and frame size in adult women: effects of body size, habitual use, and life history." Am J Hum Biol. (Special Issue on Biocultural Approaches to the Plasticity of the Human Skeleton). available in [Early View](https://doi.org/10.1002/ajhb.23502)

2020

:   Rogers, Mary P; **Lee, Katharine MN**; Galbarczyk, Andrzej; Klimek, Magdalena; Klein, Laura; Zabłocka-Słowińska, Katarzyna; Jasienska, Grazyna; Clancy, Kathryn. "Declining ages at menarche in an agrarian rural region of Poland." Am J Hum Biol. vol 32(3). [doi:10.1002/ajhb.23362](https://doi.org/10.1002/ajhb.23362)

2019

:   Richey, Christina Rae; **Lee, Katharine MN**; Rodgers, Erica; Clancy, Kathryn BH. "Gender and sexual minorities in astronomy and planetary science face increased risks of harassment and assault." Bulletin of the American Astronomical Society. [Current link (doi to be assigned soon)](https://baas.aas.org/community/gender-and-sexual-minorities-in-astronomy-and-planetary-science/)

2019

:   Rodrigues, Michelle A; Sanford, Summer R; Rogers, Mary P; **Lee, Katharine MN**; Wilson, Meredith A; Amos, Jennifer; Hunter, Carla D; Clancy, Kathryn BH. "From maternal tending to adolescent befriending: the adolescent transition of social support." Am J Primatol. [doi:10.1002/ajp.23050](https://doi.org/10.1002/ajp.23050)

2019

:   **Lee, Katharine MN**; Rogers, Mary P; Galbarczyk, Andrzej; Jasienska, Grazyna; Clancy, Kathryn BH. "Physical activity in women of reproductive age in a transitioning rural Polish population". Am J Hum Biol. 31(3):e23231.[doi: 10.1002/ajhb.23231](https://doi.org/10.1002/ajhb.23231)

2017

:   Clancy, Kathryn BH; **Lee, Katharine MN**; Rodgers, Erica; Richey, Christina Rae. "Double jeopardy in astronomy and planetary science: women of color face greater risks of gendered and racial harassment". J. Geophys. Res. Planets, 122, [doi:10.1002/2017JE005256](https://doi.org/10.1002/2017JE005256).\
    Featured in: [Physics Today](http://physicstoday.scitation.org/do/10.1063/PT.6.2.20170721a/full/), [American Scientist](https://www.americanscientist.org/article/harassment-in-science), [Eos Vox](https://eos.org/editors-vox/harassment-in-astronomy-and-planetary-science)

2009

:   Routh, R Hank; **Lee, Katharine M**; Burshell, Alan L; and Nauman, Eric A. "The effects of anti-resorptive therapies and estrogen withdrawal in adult scoliosis measured by sub-segmental vertebral BMD analysis". Bone. Vol 45, Issue 2. pp 193-199.
