---
title: "Making this site accessible and my first open-source contribution"
author: "K. Lee"
date: "2018-07-18"
---

*(note: this was written originally for my old Blog, which was written in RMarkdown and made with Blogdown. I've copied it here for the resources and a more complete record)*

I wanted to make this website both as a place to write the occassional blog post and as a place I could point people as I look for a job. As my Twitter bio says, though, I like fairness. Which for me includes working to make sure things are accessible to everyone by default.

So I reached out [on Twitter](https://twitter.com/ResourcefulSqrl/status/1019600068612063232) to ask for a tool to test my website for accessiblity for screenreaders.

Thanks to Dr. Kaitlin Stack Whitney for [recommending](https://twitter.com/KStackWhitney/status/1019600627675037696) a basic online tool to test my website! The website is <https://wave.webaim.org,> and it was super easy to use for my basic site. All you have to do is go to that site and put in your URL you want to check and it does a basic check of your page. They also have "Site-wide WAVE Tools", but I didn't go down that rabbit-hole today.

When checking for accessibility, the only problem my site had was that there was an image missing alternative text. Unfortunately, that image wasn't part of my site, but instead was part of the footer generated by the [Blogdown](https://github.com/rstudio/blogdown/) default theme that I installed working from the [Blogdown book](https://bookdown.org/yihui/blogdown/).

Thus, I was presented with a dilemma. I could fix the alternative text on my website, but that would mean all the other sites generated from that [theme](https://github.com/yihui/hugo-lithium) would still be slightly less accessible. I decided the better thing to do would be to submit a change to the theme fixing image-link by adding the alternative text.

This is a nice time to mention I've never done any sort of open-source contributions. So I winged it. I went to the github site for the theme, found the appropriate location for the image in the html code, Googled how to add alternative text to the html code, and submitted a pull request (I think that's the git-term for what I did) with my change.

And thus, that is how checking my website for accessiblility led to my first open-source contribution. Now I just have to fix it on my website, too...
